//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercializadora_Soap_Dotnet.BanQuitoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaValidacion", Namespace="http://schemas.datacontract.org/2004/07/BanQuito_Soap_Dotnet.ec.edu.monster.model" +
        "o")]
    [System.SerializableAttribute()]
    public partial class respuestaValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsSujetoCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RazonesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsSujetoCredito {
            get {
                return this.EsSujetoCreditoField;
            }
            set {
                if ((this.EsSujetoCreditoField.Equals(value) != true)) {
                    this.EsSujetoCreditoField = value;
                    this.RaisePropertyChanged("EsSujetoCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Razones {
            get {
                return this.RazonesField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonesField, value) != true)) {
                    this.RazonesField = value;
                    this.RaisePropertyChanged("Razones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaCredito", Namespace="http://schemas.datacontract.org/2004/07/BanQuito_Soap_Dotnet.ec.edu.monster.model" +
        "o")]
    [System.SerializableAttribute()]
    public partial class respuestaCredito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AprobadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CuotaMensualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aprobado {
            get {
                return this.AprobadoField;
            }
            set {
                if ((this.AprobadoField.Equals(value) != true)) {
                    this.AprobadoField = value;
                    this.RaisePropertyChanged("Aprobado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int IdCredito {
            get {
                return this.IdCreditoField;
            }
            set {
                if ((this.IdCreditoField.Equals(value) != true)) {
                    this.IdCreditoField = value;
                    this.RaisePropertyChanged("IdCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double CuotaMensual {
            get {
                return this.CuotaMensualField;
            }
            set {
                if ((this.CuotaMensualField.Equals(value) != true)) {
                    this.CuotaMensualField = value;
                    this.RaisePropertyChanged("CuotaMensual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tablaAmortizacion", Namespace="http://schemas.datacontract.org/2004/07/BanQuito_Soap_Dotnet.ec.edu.monster.model" +
        "o")]
    [System.SerializableAttribute()]
    public partial class tablaAmortizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAmortizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InteresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CapitalPagadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAmortizacion {
            get {
                return this.IdAmortizacionField;
            }
            set {
                if ((this.IdAmortizacionField.Equals(value) != true)) {
                    this.IdAmortizacionField = value;
                    this.RaisePropertyChanged("IdAmortizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCredito {
            get {
                return this.IdCreditoField;
            }
            set {
                if ((this.IdCreditoField.Equals(value) != true)) {
                    this.IdCreditoField = value;
                    this.RaisePropertyChanged("IdCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuota {
            get {
                return this.NumeroCuotaField;
            }
            set {
                if ((this.NumeroCuotaField.Equals(value) != true)) {
                    this.NumeroCuotaField = value;
                    this.RaisePropertyChanged("NumeroCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCuota {
            get {
                return this.ValorCuotaField;
            }
            set {
                if ((this.ValorCuotaField.Equals(value) != true)) {
                    this.ValorCuotaField = value;
                    this.RaisePropertyChanged("ValorCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal Interes {
            get {
                return this.InteresField;
            }
            set {
                if ((this.InteresField.Equals(value) != true)) {
                    this.InteresField = value;
                    this.RaisePropertyChanged("Interes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal CapitalPagado {
            get {
                return this.CapitalPagadoField;
            }
            set {
                if ((this.CapitalPagadoField.Equals(value) != true)) {
                    this.CapitalPagadoField = value;
                    this.RaisePropertyChanged("CapitalPagado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BanQuitoServiceReference.IBanQuitoWS")]
    public interface IBanQuitoWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ValidarSujetoCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/ValidarSujetoCreditoResponse")]
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion ValidarSujetoCredito(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ValidarSujetoCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/ValidarSujetoCreditoResponse")]
        System.Threading.Tasks.Task<Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion> ValidarSujetoCreditoAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ObtenerMontoMaximoCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/ObtenerMontoMaximoCreditoResponse")]
        double ObtenerMontoMaximoCredito(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ObtenerMontoMaximoCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/ObtenerMontoMaximoCreditoResponse")]
        System.Threading.Tasks.Task<double> ObtenerMontoMaximoCreditoAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/OtorgarCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/OtorgarCreditoResponse")]
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito OtorgarCredito(string cedula, double precioElectrodomestico, int numeroCuotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/OtorgarCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/OtorgarCreditoResponse")]
        System.Threading.Tasks.Task<Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito> OtorgarCreditoAsync(string cedula, double precioElectrodomestico, int numeroCuotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ObtenerTablaAmortizacion", ReplyAction="http://tempuri.org/IBanQuitoWS/ObtenerTablaAmortizacionResponse")]
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[] ObtenerTablaAmortizacion(int idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ObtenerTablaAmortizacion", ReplyAction="http://tempuri.org/IBanQuitoWS/ObtenerTablaAmortizacionResponse")]
        System.Threading.Tasks.Task<Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[]> ObtenerTablaAmortizacionAsync(int idCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/Health", ReplyAction="http://tempuri.org/IBanQuitoWS/HealthResponse")]
        string Health();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/Health", ReplyAction="http://tempuri.org/IBanQuitoWS/HealthResponse")]
        System.Threading.Tasks.Task<string> HealthAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBanQuitoWSChannel : Comercializadora_Soap_Dotnet.BanQuitoServiceReference.IBanQuitoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanQuitoWSClient : System.ServiceModel.ClientBase<Comercializadora_Soap_Dotnet.BanQuitoServiceReference.IBanQuitoWS>, Comercializadora_Soap_Dotnet.BanQuitoServiceReference.IBanQuitoWS {
        
        public BanQuitoWSClient() {
        }
        
        public BanQuitoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanQuitoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanQuitoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanQuitoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion ValidarSujetoCredito(string cedula) {
            return base.Channel.ValidarSujetoCredito(cedula);
        }
        
        public System.Threading.Tasks.Task<Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion> ValidarSujetoCreditoAsync(string cedula) {
            return base.Channel.ValidarSujetoCreditoAsync(cedula);
        }
        
        public double ObtenerMontoMaximoCredito(string cedula) {
            return base.Channel.ObtenerMontoMaximoCredito(cedula);
        }
        
        public System.Threading.Tasks.Task<double> ObtenerMontoMaximoCreditoAsync(string cedula) {
            return base.Channel.ObtenerMontoMaximoCreditoAsync(cedula);
        }
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito OtorgarCredito(string cedula, double precioElectrodomestico, int numeroCuotas) {
            return base.Channel.OtorgarCredito(cedula, precioElectrodomestico, numeroCuotas);
        }
        
        public System.Threading.Tasks.Task<Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito> OtorgarCreditoAsync(string cedula, double precioElectrodomestico, int numeroCuotas) {
            return base.Channel.OtorgarCreditoAsync(cedula, precioElectrodomestico, numeroCuotas);
        }
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[] ObtenerTablaAmortizacion(int idCredito) {
            return base.Channel.ObtenerTablaAmortizacion(idCredito);
        }
        
        public System.Threading.Tasks.Task<Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[]> ObtenerTablaAmortizacionAsync(int idCredito) {
            return base.Channel.ObtenerTablaAmortizacionAsync(idCredito);
        }
        
        public string Health() {
            return base.Channel.Health();
        }
        
        public System.Threading.Tasks.Task<string> HealthAsync() {
            return base.Channel.HealthAsync();
        }
    }
}
