//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercializadora_Soap_Dotnet.BanQuitoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaValidacion", Namespace="http://schemas.datacontract.org/2004/07/BanQuito_Soap_Dotnet.ec.edu.espe.modelo")]
    [System.SerializableAttribute()]
    public partial class respuestaValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsSujetoCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RazonesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsSujetoCredito {
            get {
                return this.EsSujetoCreditoField;
            }
            set {
                if ((this.EsSujetoCreditoField.Equals(value) != true)) {
                    this.EsSujetoCreditoField = value;
                    this.RaisePropertyChanged("EsSujetoCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Razones {
            get {
                return this.RazonesField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonesField, value) != true)) {
                    this.RazonesField = value;
                    this.RaisePropertyChanged("Razones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaCredito", Namespace="http://schemas.datacontract.org/2004/07/BanQuito_Soap_Dotnet.ec.edu.espe.modelo")]
    [System.SerializableAttribute()]
    public partial class respuestaCredito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AprobadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CuotaMensualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aprobado {
            get {
                return this.AprobadoField;
            }
            set {
                if ((this.AprobadoField.Equals(value) != true)) {
                    this.AprobadoField = value;
                    this.RaisePropertyChanged("Aprobado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int IdCredito {
            get {
                return this.IdCreditoField;
            }
            set {
                if ((this.IdCreditoField.Equals(value) != true)) {
                    this.IdCreditoField = value;
                    this.RaisePropertyChanged("IdCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double CuotaMensual {
            get {
                return this.CuotaMensualField;
            }
            set {
                if ((this.CuotaMensualField.Equals(value) != true)) {
                    this.CuotaMensualField = value;
                    this.RaisePropertyChanged("CuotaMensual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tablaAmortizacion", Namespace="http://schemas.datacontract.org/2004/07/BanQuito_Soap_Dotnet.ec.edu.espe.modelo")]
    [System.SerializableAttribute()]
    public partial class tablaAmortizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAmortizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InteresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CapitalPagadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAmortizacion {
            get {
                return this.IdAmortizacionField;
            }
            set {
                if ((this.IdAmortizacionField.Equals(value) != true)) {
                    this.IdAmortizacionField = value;
                    this.RaisePropertyChanged("IdAmortizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCredito {
            get {
                return this.IdCreditoField;
            }
            set {
                if ((this.IdCreditoField.Equals(value) != true)) {
                    this.IdCreditoField = value;
                    this.RaisePropertyChanged("IdCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuota {
            get {
                return this.NumeroCuotaField;
            }
            set {
                if ((this.NumeroCuotaField.Equals(value) != true)) {
                    this.NumeroCuotaField = value;
                    this.RaisePropertyChanged("NumeroCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCuota {
            get {
                return this.ValorCuotaField;
            }
            set {
                if ((this.ValorCuotaField.Equals(value) != true)) {
                    this.ValorCuotaField = value;
                    this.RaisePropertyChanged("ValorCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal Interes {
            get {
                return this.InteresField;
            }
            set {
                if ((this.InteresField.Equals(value) != true)) {
                    this.InteresField = value;
                    this.RaisePropertyChanged("Interes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal CapitalPagado {
            get {
                return this.CapitalPagadoField;
            }
            set {
                if ((this.CapitalPagadoField.Equals(value) != true)) {
                    this.CapitalPagadoField = value;
                    this.RaisePropertyChanged("CapitalPagado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BanQuitoServiceReference.IBanQuitoWS")]
    public interface IBanQuitoWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ValidarSujetoCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/ValidarSujetoCreditoResponse")]
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion ValidarSujetoCredito(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBanQuitoWS/ValidarSujetoCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/ValidarSujetoCreditoResponse")]
        System.IAsyncResult BeginValidarSujetoCredito(string cedula, System.AsyncCallback callback, object asyncState);
        
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion EndValidarSujetoCredito(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ObtenerMontoMaximoCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/ObtenerMontoMaximoCreditoResponse")]
        double ObtenerMontoMaximoCredito(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBanQuitoWS/ObtenerMontoMaximoCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/ObtenerMontoMaximoCreditoResponse")]
        System.IAsyncResult BeginObtenerMontoMaximoCredito(string cedula, System.AsyncCallback callback, object asyncState);
        
        double EndObtenerMontoMaximoCredito(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/OtorgarCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/OtorgarCreditoResponse")]
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito OtorgarCredito(string cedula, double precioElectrodomestico, int numeroCuotas);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBanQuitoWS/OtorgarCredito", ReplyAction="http://tempuri.org/IBanQuitoWS/OtorgarCreditoResponse")]
        System.IAsyncResult BeginOtorgarCredito(string cedula, double precioElectrodomestico, int numeroCuotas, System.AsyncCallback callback, object asyncState);
        
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito EndOtorgarCredito(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/ObtenerTablaAmortizacion", ReplyAction="http://tempuri.org/IBanQuitoWS/ObtenerTablaAmortizacionResponse")]
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[] ObtenerTablaAmortizacion(int idCredito);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBanQuitoWS/ObtenerTablaAmortizacion", ReplyAction="http://tempuri.org/IBanQuitoWS/ObtenerTablaAmortizacionResponse")]
        System.IAsyncResult BeginObtenerTablaAmortizacion(int idCredito, System.AsyncCallback callback, object asyncState);
        
        Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[] EndObtenerTablaAmortizacion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBanQuitoWS/Health", ReplyAction="http://tempuri.org/IBanQuitoWS/HealthResponse")]
        string Health();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBanQuitoWS/Health", ReplyAction="http://tempuri.org/IBanQuitoWS/HealthResponse")]
        System.IAsyncResult BeginHealth(System.AsyncCallback callback, object asyncState);
        
        string EndHealth(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBanQuitoWSChannel : Comercializadora_Soap_Dotnet.BanQuitoServiceReference.IBanQuitoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidarSujetoCreditoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidarSujetoCreditoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerMontoMaximoCreditoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerMontoMaximoCreditoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OtorgarCreditoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public OtorgarCreditoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerTablaAmortizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerTablaAmortizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HealthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HealthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanQuitoWSClient : System.ServiceModel.ClientBase<Comercializadora_Soap_Dotnet.BanQuitoServiceReference.IBanQuitoWS>, Comercializadora_Soap_Dotnet.BanQuitoServiceReference.IBanQuitoWS {
        
        private BeginOperationDelegate onBeginValidarSujetoCreditoDelegate;
        
        private EndOperationDelegate onEndValidarSujetoCreditoDelegate;
        
        private System.Threading.SendOrPostCallback onValidarSujetoCreditoCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerMontoMaximoCreditoDelegate;
        
        private EndOperationDelegate onEndObtenerMontoMaximoCreditoDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerMontoMaximoCreditoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOtorgarCreditoDelegate;
        
        private EndOperationDelegate onEndOtorgarCreditoDelegate;
        
        private System.Threading.SendOrPostCallback onOtorgarCreditoCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerTablaAmortizacionDelegate;
        
        private EndOperationDelegate onEndObtenerTablaAmortizacionDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerTablaAmortizacionCompletedDelegate;
        
        private BeginOperationDelegate onBeginHealthDelegate;
        
        private EndOperationDelegate onEndHealthDelegate;
        
        private System.Threading.SendOrPostCallback onHealthCompletedDelegate;
        
        public BanQuitoWSClient() {
        }
        
        public BanQuitoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanQuitoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanQuitoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanQuitoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ValidarSujetoCreditoCompletedEventArgs> ValidarSujetoCreditoCompleted;
        
        public event System.EventHandler<ObtenerMontoMaximoCreditoCompletedEventArgs> ObtenerMontoMaximoCreditoCompleted;
        
        public event System.EventHandler<OtorgarCreditoCompletedEventArgs> OtorgarCreditoCompleted;
        
        public event System.EventHandler<ObtenerTablaAmortizacionCompletedEventArgs> ObtenerTablaAmortizacionCompleted;
        
        public event System.EventHandler<HealthCompletedEventArgs> HealthCompleted;
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion ValidarSujetoCredito(string cedula) {
            return base.Channel.ValidarSujetoCredito(cedula);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginValidarSujetoCredito(string cedula, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidarSujetoCredito(cedula, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion EndValidarSujetoCredito(System.IAsyncResult result) {
            return base.Channel.EndValidarSujetoCredito(result);
        }
        
        private System.IAsyncResult OnBeginValidarSujetoCredito(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cedula = ((string)(inValues[0]));
            return this.BeginValidarSujetoCredito(cedula, callback, asyncState);
        }
        
        private object[] OnEndValidarSujetoCredito(System.IAsyncResult result) {
            Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaValidacion retVal = this.EndValidarSujetoCredito(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidarSujetoCreditoCompleted(object state) {
            if ((this.ValidarSujetoCreditoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidarSujetoCreditoCompleted(this, new ValidarSujetoCreditoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidarSujetoCreditoAsync(string cedula) {
            this.ValidarSujetoCreditoAsync(cedula, null);
        }
        
        public void ValidarSujetoCreditoAsync(string cedula, object userState) {
            if ((this.onBeginValidarSujetoCreditoDelegate == null)) {
                this.onBeginValidarSujetoCreditoDelegate = new BeginOperationDelegate(this.OnBeginValidarSujetoCredito);
            }
            if ((this.onEndValidarSujetoCreditoDelegate == null)) {
                this.onEndValidarSujetoCreditoDelegate = new EndOperationDelegate(this.OnEndValidarSujetoCredito);
            }
            if ((this.onValidarSujetoCreditoCompletedDelegate == null)) {
                this.onValidarSujetoCreditoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidarSujetoCreditoCompleted);
            }
            base.InvokeAsync(this.onBeginValidarSujetoCreditoDelegate, new object[] {
                        cedula}, this.onEndValidarSujetoCreditoDelegate, this.onValidarSujetoCreditoCompletedDelegate, userState);
        }
        
        public double ObtenerMontoMaximoCredito(string cedula) {
            return base.Channel.ObtenerMontoMaximoCredito(cedula);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerMontoMaximoCredito(string cedula, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerMontoMaximoCredito(cedula, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public double EndObtenerMontoMaximoCredito(System.IAsyncResult result) {
            return base.Channel.EndObtenerMontoMaximoCredito(result);
        }
        
        private System.IAsyncResult OnBeginObtenerMontoMaximoCredito(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cedula = ((string)(inValues[0]));
            return this.BeginObtenerMontoMaximoCredito(cedula, callback, asyncState);
        }
        
        private object[] OnEndObtenerMontoMaximoCredito(System.IAsyncResult result) {
            double retVal = this.EndObtenerMontoMaximoCredito(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerMontoMaximoCreditoCompleted(object state) {
            if ((this.ObtenerMontoMaximoCreditoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerMontoMaximoCreditoCompleted(this, new ObtenerMontoMaximoCreditoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerMontoMaximoCreditoAsync(string cedula) {
            this.ObtenerMontoMaximoCreditoAsync(cedula, null);
        }
        
        public void ObtenerMontoMaximoCreditoAsync(string cedula, object userState) {
            if ((this.onBeginObtenerMontoMaximoCreditoDelegate == null)) {
                this.onBeginObtenerMontoMaximoCreditoDelegate = new BeginOperationDelegate(this.OnBeginObtenerMontoMaximoCredito);
            }
            if ((this.onEndObtenerMontoMaximoCreditoDelegate == null)) {
                this.onEndObtenerMontoMaximoCreditoDelegate = new EndOperationDelegate(this.OnEndObtenerMontoMaximoCredito);
            }
            if ((this.onObtenerMontoMaximoCreditoCompletedDelegate == null)) {
                this.onObtenerMontoMaximoCreditoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerMontoMaximoCreditoCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerMontoMaximoCreditoDelegate, new object[] {
                        cedula}, this.onEndObtenerMontoMaximoCreditoDelegate, this.onObtenerMontoMaximoCreditoCompletedDelegate, userState);
        }
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito OtorgarCredito(string cedula, double precioElectrodomestico, int numeroCuotas) {
            return base.Channel.OtorgarCredito(cedula, precioElectrodomestico, numeroCuotas);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginOtorgarCredito(string cedula, double precioElectrodomestico, int numeroCuotas, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginOtorgarCredito(cedula, precioElectrodomestico, numeroCuotas, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito EndOtorgarCredito(System.IAsyncResult result) {
            return base.Channel.EndOtorgarCredito(result);
        }
        
        private System.IAsyncResult OnBeginOtorgarCredito(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cedula = ((string)(inValues[0]));
            double precioElectrodomestico = ((double)(inValues[1]));
            int numeroCuotas = ((int)(inValues[2]));
            return this.BeginOtorgarCredito(cedula, precioElectrodomestico, numeroCuotas, callback, asyncState);
        }
        
        private object[] OnEndOtorgarCredito(System.IAsyncResult result) {
            Comercializadora_Soap_Dotnet.BanQuitoServiceReference.respuestaCredito retVal = this.EndOtorgarCredito(result);
            return new object[] {
                    retVal};
        }
        
        private void OnOtorgarCreditoCompleted(object state) {
            if ((this.OtorgarCreditoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OtorgarCreditoCompleted(this, new OtorgarCreditoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OtorgarCreditoAsync(string cedula, double precioElectrodomestico, int numeroCuotas) {
            this.OtorgarCreditoAsync(cedula, precioElectrodomestico, numeroCuotas, null);
        }
        
        public void OtorgarCreditoAsync(string cedula, double precioElectrodomestico, int numeroCuotas, object userState) {
            if ((this.onBeginOtorgarCreditoDelegate == null)) {
                this.onBeginOtorgarCreditoDelegate = new BeginOperationDelegate(this.OnBeginOtorgarCredito);
            }
            if ((this.onEndOtorgarCreditoDelegate == null)) {
                this.onEndOtorgarCreditoDelegate = new EndOperationDelegate(this.OnEndOtorgarCredito);
            }
            if ((this.onOtorgarCreditoCompletedDelegate == null)) {
                this.onOtorgarCreditoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOtorgarCreditoCompleted);
            }
            base.InvokeAsync(this.onBeginOtorgarCreditoDelegate, new object[] {
                        cedula,
                        precioElectrodomestico,
                        numeroCuotas}, this.onEndOtorgarCreditoDelegate, this.onOtorgarCreditoCompletedDelegate, userState);
        }
        
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[] ObtenerTablaAmortizacion(int idCredito) {
            return base.Channel.ObtenerTablaAmortizacion(idCredito);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerTablaAmortizacion(int idCredito, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerTablaAmortizacion(idCredito, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[] EndObtenerTablaAmortizacion(System.IAsyncResult result) {
            return base.Channel.EndObtenerTablaAmortizacion(result);
        }
        
        private System.IAsyncResult OnBeginObtenerTablaAmortizacion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idCredito = ((int)(inValues[0]));
            return this.BeginObtenerTablaAmortizacion(idCredito, callback, asyncState);
        }
        
        private object[] OnEndObtenerTablaAmortizacion(System.IAsyncResult result) {
            Comercializadora_Soap_Dotnet.BanQuitoServiceReference.tablaAmortizacion[] retVal = this.EndObtenerTablaAmortizacion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerTablaAmortizacionCompleted(object state) {
            if ((this.ObtenerTablaAmortizacionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerTablaAmortizacionCompleted(this, new ObtenerTablaAmortizacionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerTablaAmortizacionAsync(int idCredito) {
            this.ObtenerTablaAmortizacionAsync(idCredito, null);
        }
        
        public void ObtenerTablaAmortizacionAsync(int idCredito, object userState) {
            if ((this.onBeginObtenerTablaAmortizacionDelegate == null)) {
                this.onBeginObtenerTablaAmortizacionDelegate = new BeginOperationDelegate(this.OnBeginObtenerTablaAmortizacion);
            }
            if ((this.onEndObtenerTablaAmortizacionDelegate == null)) {
                this.onEndObtenerTablaAmortizacionDelegate = new EndOperationDelegate(this.OnEndObtenerTablaAmortizacion);
            }
            if ((this.onObtenerTablaAmortizacionCompletedDelegate == null)) {
                this.onObtenerTablaAmortizacionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerTablaAmortizacionCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerTablaAmortizacionDelegate, new object[] {
                        idCredito}, this.onEndObtenerTablaAmortizacionDelegate, this.onObtenerTablaAmortizacionCompletedDelegate, userState);
        }
        
        public string Health() {
            return base.Channel.Health();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHealth(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHealth(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHealth(System.IAsyncResult result) {
            return base.Channel.EndHealth(result);
        }
        
        private System.IAsyncResult OnBeginHealth(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHealth(callback, asyncState);
        }
        
        private object[] OnEndHealth(System.IAsyncResult result) {
            string retVal = this.EndHealth(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHealthCompleted(object state) {
            if ((this.HealthCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HealthCompleted(this, new HealthCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HealthAsync() {
            this.HealthAsync(null);
        }
        
        public void HealthAsync(object userState) {
            if ((this.onBeginHealthDelegate == null)) {
                this.onBeginHealthDelegate = new BeginOperationDelegate(this.OnBeginHealth);
            }
            if ((this.onEndHealthDelegate == null)) {
                this.onEndHealthDelegate = new EndOperationDelegate(this.OnEndHealth);
            }
            if ((this.onHealthCompletedDelegate == null)) {
                this.onHealthCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHealthCompleted);
            }
            base.InvokeAsync(this.onBeginHealthDelegate, null, this.onEndHealthDelegate, this.onHealthCompletedDelegate, userState);
        }
    }
}
